const ActionTypes = {
  // SEARCH_REQUEST: 'SEARCH_REQUEST',
  SEARCH_SUCCESS: 'SEARCH_SUCCESS',
  SEARCH_FAIL: 'SEARCH_FAIL',
  GET_MORE_SUCCESS: 'GET_MORE_SUCCESS',
  GET_MORE_FAIL: 'GET_MORE_FAIL',
  CLOSE_HOME_PAGE: 'CLOSE_HOME_PAGE',
  CHANGE_VIEW_MODE: 'CHANGE_VIEW_MODE',
  TOGGLE_LOADING_ICON: 'TOGGLE_LOADING_ICON',
  UPDATE_REQUEST_TEXT: 'UPDATE_REQUEST_TEXT',
  UPDATE_TOTAL_DATA: 'UPDATE_TOTAL_DATA',
  UPDATE_WAITING_STATUS: 'UPDATE_WAITING_STATUS',
  KEYWORD_REQUEST_SUCCESS: 'KEYWORD_REQUEST_SUCCESS',
  KEYWORD_REQUEST_FAIL: 'KEYWORD_REQUEST_FAIL',
  KEYWORD_REQUEST_CLEAR: 'KEYWORD_REQUEST_CLEAR'
};

export default ActionTypes;
